services:
  # Frontend (Angular) - Port 4200 hit karega Aspire Gateway ko
  hr-frontend:
    build:
      context: D:/hr-ui
      dockerfile: Dockerfile
    container_name: hr-frontend
    ports:
      - "4200:80"
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge