// <auto-generated />
using System;
using HR.Payroll.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HR.Payroll.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005105859_AddLoanRequestsAndPolicy")]
    partial class AddLoanRequestsAndPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payroll")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HR.Payroll.API.Domain.Employees.PayrollEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("EmployeeId");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BankAccountTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DesignationTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Iban")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PayGroupId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PayGroupId");

                    b.HasIndex("TenantId", "EmployeeCode")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("TenantId", "PayGroupId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "PayGroupId"), new[] { "IsActive", "JoiningDate", "ExitDate" });

                    b.ToTable("PayrollEmployees", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.EmployeeLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<Guid>("DeductionComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("LoanType")
                        .HasColumnType("smallint");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeductionComponentId");

                    b.HasIndex("EmployeeId")
                        .HasFilter("[Status] = 1 AND \"IsDeleted\" = false");

                    b.ToTable("EmployeeLoans", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_Loans_Amounts", "[PrincipalAmount] > 0 AND [InstallmentAmount] > 0 AND [OutstandingAmount] BETWEEN 0 AND [PrincipalAmount]");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.LoanPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdvanceDeductionComponentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AdvancesEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMultipleActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoanDeductionComponentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LoansEnabled")
                        .HasColumnType("boolean");

                    b.Property<byte>("MaxAdvanceInstallments")
                        .HasColumnType("smallint");

                    b.Property<decimal>("MaxAdvancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MaxLoanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("MaxLoanInstallments")
                        .HasColumnType("smallint");

                    b.Property<byte?>("MaxLoanSalaryMultiple")
                        .HasColumnType("smallint");

                    b.Property<short>("MinServiceMonths")
                        .HasColumnType("smallint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvanceDeductionComponentId");

                    b.HasIndex("LoanDeductionComponentId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("LoanPolicies", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_LoanPolicies_Advance", "\"MaxAdvancePercent\" > 0 AND \"MaxAdvancePercent\" <= 100");

                            t.HasCheckConstraint("CK_LoanPolicies_Installments", "\"MaxLoanInstallments\" BETWEEN 1 AND 120 AND \"MaxAdvanceInstallments\" BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.LoanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ApprovedInstallmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DecidedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeLoanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("LoanType")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("PreferredStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("RequestedInstallments")
                        .HasColumnType("smallint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeLoanId")
                        .IsUnique()
                        .HasFilter("\"EmployeeLoanId\" IS NOT NULL");

                    b.HasIndex("EmployeeId", "CreatedAt");

                    b.HasIndex("TenantId", "Status")
                        .HasFilter("\"Status\" = 1 AND \"IsDeleted\" = false");

                    b.ToTable("LoanRequests", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_LoanRequests_Amounts", "\"RequestedAmount\" > 0 AND \"RequestedInstallments\" BETWEEN 1 AND 120");

                            t.HasCheckConstraint("CK_LoanRequests_Approved", "\"Status\" <> 2 OR (\"EmployeeLoanId\" IS NOT NULL AND \"ApprovedAmount\" > 0 AND \"ApprovedInstallmentAmount\" > 0)");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.PayrollInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PayComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayPeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("Source")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayComponentId");

                    b.HasIndex("PayPeriodId", "EmployeeId", "PayComponentId", "Source", "SourceReference")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("PayrollInputs", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_PayrollInputs_Value", "\"Amount\" IS NOT NULL OR \"Quantity\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.UnpaidLeaveDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DayFraction")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "LeaveDate");

                    b.HasIndex("LeaveRequestId", "LeaveDate")
                        .IsUnique();

                    b.ToTable("EmployeeUnpaidLeaveDays", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_UnpaidLeaveDay", "\"DayFraction\" IN (0.50, 1.00)");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte>("Method")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("PaymentBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentBatchId");

                    b.HasIndex("PayslipId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1, 2) AND \"IsDeleted\" = false");

                    b.ToTable("Payments", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Payments.PaymentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<byte>("FileFormat")
                        .HasColumnType("smallint");

                    b.Property<string>("FileStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("PaymentBatches", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.LoanRepayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeLoanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayslipId");

                    b.HasIndex("EmployeeLoanId", "PayslipId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("LoanRepayments", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_LoanRepayment", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("PayGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayPeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessedEmployees")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("RunType")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEmployerCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalGross")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayGroupId");

                    b.HasIndex("PayPeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_Runs_RegularPerPeriod")
                        .HasFilter("[RunType] = 1 AND [Status] <> 6 AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "Status");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "Status"), new[] { "PayGroupId", "PayPeriodId" });

                    b.ToTable("PayrollRuns", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_Runs_Status", "\"Status\" BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccountMasked")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DesignationTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("EmployerContributions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("GrossEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PayableDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayslipNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("PeriodDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxableIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnpaidLeaveDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "PeriodStart")
                        .IsDescending(false, true);

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("EmployeeId", "PeriodStart"), new[] { "NetPay", "Status" });

                    b.HasIndex("PayrollRunId", "EmployeeId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("TenantId", "PayslipNumber")
                        .IsUnique();

                    b.ToTable("Payslips", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_Payslips_Net", "\"NetPay\" = \"GrossEarnings\" - \"TotalDeductions\"");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.PayslipLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("ComponentType")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PayComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<byte>("Source")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SourceReference")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayComponentId");

                    b.HasIndex("PayslipId");

                    b.ToTable("PayslipLines", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasisAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte>("ChangeReason")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("SalaryBasis")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SalaryGradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaryTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmpSalary_Current")
                        .HasFilter("[EffectiveTo] IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("SalaryGradeId");

                    b.HasIndex("SalaryTemplateId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsDescending(false, true);

                    b.ToTable("EmployeeSalaries", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_EmpSalary_Amount", "\"BasisAmount\" > 0");

                            t.HasCheckConstraint("CK_EmpSalary_Dates", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" >= \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.EmployeeSalaryComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BaseComponentId")
                        .HasColumnType("uuid");

                    b.Property<byte?>("CalcType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("EmployeeSalaryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PayComponentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("BaseComponentId");

                    b.HasIndex("PayComponentId");

                    b.HasIndex("EmployeeSalaryId", "PayComponentId")
                        .IsUnique();

                    b.ToTable("EmployeeSalaryComponents", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxAnnual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinAnnual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("SalaryGrades", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SalaryGradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SalaryGradeId");

                    b.ToTable("SalaryTemplates", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryTemplateLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BaseComponentId")
                        .HasColumnType("uuid");

                    b.Property<byte>("CalcType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("PayComponentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid>("SalaryTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseComponentId");

                    b.HasIndex("PayComponentId");

                    b.HasIndex("SalaryTemplateId", "PayComponentId")
                        .IsUnique();

                    b.ToTable("SalaryTemplateLines", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Setup.PayComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("ComponentType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultBaseComponentId")
                        .HasColumnType("uuid");

                    b.Property<byte>("DefaultCalcType")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProrated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("ShowOnPayslip")
                        .HasColumnType("boolean");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("SystemCode")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PayComponents", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Setup.PayGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AnchorDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("PayDayOffset")
                        .HasColumnType("smallint");

                    b.Property<byte>("PayFrequency")
                        .HasColumnType("smallint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PayGroups", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Setup.PayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<short>("FiscalYear")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PayGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<byte>("PeriodNumber")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PayPeriods", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Setup.PayrollSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PayslipNumberPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("ProrationMethod")
                        .HasColumnType("smallint");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("boolean");

                    b.Property<byte>("RoundingDecimals")
                        .HasColumnType("smallint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PayrollSettings", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.ContributionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("BaseType")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployeeComponentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EmployeeFixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("EmployeeRatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid?>("EmployerComponentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EmployerFixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("EmployerRatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOptIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WageCeiling")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeComponentId");

                    b.HasIndex("EmployerComponentId");

                    b.HasIndex("CountryCode", "Code", "EffectiveFrom");

                    b.ToTable("ContributionRules", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.EmployeeTaxOpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriorTaxPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriorTaxableIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("TaxYearStart")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "TaxYearStart")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("EmployeeTaxOpeningBalances", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.TaxRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("CalcMethod")
                        .HasColumnType("smallint");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte>("TaxYearStartMonth")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "EffectiveFrom");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CountryCode", "EffectiveFrom"), new[] { "TenantId", "EffectiveTo", "IsActive" });

                    b.ToTable("TaxRegimes", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_TaxRegimes_Month", "\"TaxYearStartMonth\" BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.TaxSlab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FromAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid>("TaxRegimeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ToAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxRegimeId", "FromAmount")
                        .IsUnique();

                    b.ToTable("TaxSlabs", "payroll", t =>
                        {
                            t.HasCheckConstraint("CK_TaxSlab", "\"ToAmount\" IS NULL OR \"ToAmount\" > \"FromAmount\"");
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "payroll");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "payroll");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "payroll");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Employees.PayrollEmployee", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayGroup", null)
                        .WithMany()
                        .HasForeignKey("PayGroupId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.EmployeeLoan", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("DeductionComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.LoanPolicy", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("AdvanceDeductionComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("LoanDeductionComponentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.LoanRequest", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Inputs.EmployeeLoan", null)
                        .WithMany()
                        .HasForeignKey("EmployeeLoanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.PayrollInput", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayPeriod", null)
                        .WithMany()
                        .HasForeignKey("PayPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Inputs.UnpaidLeaveDay", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Payments.Payment", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Payments.PaymentBatch", null)
                        .WithMany()
                        .HasForeignKey("PaymentBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Runs.Payslip", null)
                        .WithMany()
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Payments.PaymentBatch", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Runs.PayrollRun", null)
                        .WithMany()
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.LoanRepayment", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Inputs.EmployeeLoan", null)
                        .WithMany()
                        .HasForeignKey("EmployeeLoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Runs.Payslip", null)
                        .WithMany()
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.PayrollRun", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayGroup", null)
                        .WithMany()
                        .HasForeignKey("PayGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayPeriod", null)
                        .WithMany()
                        .HasForeignKey("PayPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.Payslip", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Runs.PayrollRun", null)
                        .WithMany()
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.PayslipLine", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Runs.Payslip", null)
                        .WithMany("Lines")
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.EmployeeSalary", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Salaries.SalaryGrade", null)
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Salaries.SalaryTemplate", null)
                        .WithMany()
                        .HasForeignKey("SalaryTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.EmployeeSalaryComponent", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("BaseComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Salaries.EmployeeSalary", null)
                        .WithMany("Overrides")
                        .HasForeignKey("EmployeeSalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryTemplate", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Salaries.SalaryGrade", null)
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryTemplateLine", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("BaseComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Payroll.API.Domain.Salaries.SalaryTemplate", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalaryTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.ContributionRule", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("EmployeeComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HR.Payroll.API.Domain.Setup.PayComponent", null)
                        .WithMany()
                        .HasForeignKey("EmployerComponentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.EmployeeTaxOpeningBalance", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Employees.PayrollEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.TaxSlab", b =>
                {
                    b.HasOne("HR.Payroll.API.Domain.Tax.TaxRegime", null)
                        .WithMany("Slabs")
                        .HasForeignKey("TaxRegimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Runs.Payslip", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.EmployeeSalary", b =>
                {
                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Salaries.SalaryTemplate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HR.Payroll.API.Domain.Tax.TaxRegime", b =>
                {
                    b.Navigation("Slabs");
                });
#pragma warning restore 612, 618
        }
    }
}
